#!/usr/bin/with-contenv bash

# install easyepg

[[ ! -e /easyepg/epg.sh ]] && \
	wget -O /tmp/easyepg.zip https://github.com/sunsettrack4/easyepg/archive/v$EEPG_VER.zip && \
	unzip /tmp/easyepg.zip -d /tmp && \
	mv /tmp/easyepg-$EEPG_VER/* /easyepg/ && \
	rm -R /tmp/* && 


# add cron file for running easyepg
[[ ! -e /easyepg/ee-cron ]] && \
	cp /defaults/ee-cron /easyepg/ee-cron
crontab /easyepg/ee-cron

# Update easyepg
/bin/bash /defaults/update.sh

# permissions
chmod -R 777 /easyepg
chown -R abc:abc \
	/easyepg

chown -R abc:abc \
	/tmp
